# This is a basic workflow to help you get started with Actions

name: Sync github actions and update gitee pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "gh-pages" branch
  push:
    branches: ["gh-pages"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        REPOSITORY_NAME: dzlkuboy/git@github.com:dzlkuboy/amazing-sentences.git
        BRANCH: gh-pages
        FOLDER: docs/.vitepress/dist/